### ISSUE TITLE
DearImGuiKnobs header problem with Makefile

### ISSUE THREAD

**Issue by noisecode3** [DISTRHO/DPF-Widgets#7]
I had to change the includes to use a leading ../ `#include "../DearImGui/imgui.h"`
There can also be just symbolic links. With the Makefile build I can't change
```
BUILD_C_FLAGS
BUILD_CXX_FLAGS
```
before `include ../../dpf/Makefile.plugins.mk `  cus it will overwrite it.

When I set `#define DISTRHO_UI_CUSTOM_INCLUDE_PATH "../../dpf-widgets/opengl/DearImGui.hpp" `
it works with normal Makefile  and I have to make sure it builds dpf with  `$(MAKE) -C dpf/dgl opengl`
or `$(MAKE) -C dpf/dgl opengl3`
and for lv2 I have to specify lv2_sep

**Comment by falkTX** [comment]
you can add flags after including the `Makefile.plugins.mk` to specify extra paths to include.
for example https://github.com/DISTRHO/OneKnob-Series/blob/main/plugins/AB-InputSelector/Makefile#L25

Then the custom path macros won't need "../" anymore

**Comment by falkTX** [comment]
Forgot to close this ticket, and anyway since there was no more feedback I assume the issue has been resolved
